### ISSUE TITLE
Symbolの紹介文を用意しませんか

### ISSUE THREAD

**Issue by ymuichiro** [ymuichiro/symbol_japan_forum#1]
## 提案事項
このGithubのトップページのように、Symbolを紹介する時に、100~200字程度の紹介文があるといいのに、と考えています。
Symbolの特徴を伝えられるような平易かつ、シンプルな紹介文を作りませんか。

## 要求
Symbolの特徴を表すキーワードの提供や文案があれば頂けないでしょうか

## 用途
まずはこのGithubのトップページに紹介文を掲載致します。また、各個人が自身のTwitterやNoteでSymbolを紹介する際に、各個人の判断のもと、利用される事を想定しています

**Comment by ymuichiro** [comment]
discord connect test

**Comment by dusanjp** [comment]
とりあえず記念ｶｷｺw

**Comment by ymuichiro** [comment]
一番槍は づーさん となりました！

**Comment by dusanjp** [comment]
わはは

**Comment by HANABATAKE-jp** [comment]
入れた❗️

**Comment by D-laplace666** [comment]
配信中、コメントtest

**Comment by ymuichiro** [comment]
取り急ぎSymbol紹介文の文案を作成致しました
こんな感じだとどうだろう。私自身まだまだSymbolは勉強中なところがあるので、ここ魅力だろう！とかそこ違うだろう！は是非頂きたい

```
Symbolは2021年にブロックチェーン"NEM"の後継として登場しました。特徴はnつあります。1つは利用する際の障壁の低さです。Symbolはそのシステムに堅牢かつ多機能な取引制御ロジックが組み込まれている為、自分で難しいプログラムを行わずとも簡単かつ安全に利用する事が出来ます。次に合理的かつ環境に優しいなコンセンサスアルゴリズムの存在です。Symbolは特徴的なアルゴリズムとしてPoS+という方式で実装しています。これはPoW等と異なり、チェーンへの参加者の貢献度や信頼度を数学的に算出してチェーンへのデータ追加を"承認"しています。その他、取引実行時の取引が安価、豊富なデータを組み込む事も可能といったモダンなチェーンであり、その利便性からユースケースが拡大しているブロックチェーンです
```

**Comment by YUTOpian** [comment]
Wikipediaの書き方も参考にできるかなと思っています

https://ja.wikipedia.org/wiki/Symbol_(%E3%83%96%E3%83%AD%E3%83%83%E3%82%AF%E3%83%81%E3%82%A7%E3%83%BC%E3%83%B3)

**Comment by ymuichiro** [comment]
@YUTOpian 
wikipedia のはちょっとエンジニアか詳しい人向けって感じかな
結構専門用語多めの解説になっていると思っていますが、これをいい感じに要約できんかな...
