### ISSUE TITLE
ウォレットのより安全、セキュアな管理方法の検討

### ISSUE THREAD

**Issue by ymuichiro** [ymuichiro/symbol_japan_forum#11]
Symbolや暗号資産ウォレットのよりセキュアな、安全な管理方法の確立にむけて案を出し合いませんか

今後ウォレットに大量のXYMを保有する方も出てくると思いますので適当な管理方法を模索する必要があると感じています

**Comment by Cat-008** [comment]
知りたいです。
例えばお遊び用のウォレットは、アドレス分けるのはもちろんですが、アカウントごと別にしたほうがよいのか。など🥺

**Comment by mash-ym** [comment]
以前Twitterで見かけましたが、マルチシグで出金制限をすると良いとみました。
まだ詳しく調べられてないです…

**Comment by Cat-008** [comment]
ありがとうございます！
マルチシグの設定…しといたほうが良いと聞いているものの、設定が怖いということは自身の勉強不足なんだろうな

まめしばさんの動画見て勉強します🐱

[https://youtu.be/b3Ie6kW1-k0](まめしばラボ)

**Comment by YoBi-185** [comment]
マルチシグとか色んなのは少し手間ですが、テストネットでいじり倒してある程度分かってからだと安心ですよ😆

**Comment by 0x070696E65** [comment]
一番多く入れてるのは2of3のマルチシグにしてますね。
・デスクトップウォレットの署名用アカウント
・LedgerNano
・スマホ
で一応分けてます。
他のアカウントは何もしてないかわりに最悪なくなっても一晩悲しんで忘れられるぐらいにしてます😅

**Comment by ymuichiro** [comment]
@0x070696E65 LedgerNano噛ませるのいいですね！私も今度それ考えよう

**Comment by Cat-008** [comment]
やっぱり外部ウォレットが最強なのかな。テストネットで色々触ることも仕組みが理解できて有意義そうですね！

実体験に基づくご意見、大変貴重で参考になります。ありがとうございます(^^)

**Comment by ymuichiro** [comment]
これはとても参考になったので置いておきます
https://qiita.com/nem_takanobu/items/a732fe1c21ebe684e13a

**Comment by ymuichiro** [comment]
なるべくなるべく読むハードルを下げるべく、絵にして簡単な解説をつけたんだけどどうだろう

![名称未設定](https://user-images.githubusercontent.com/47295014/166250746-23021500-70c5-4d1f-bab6-1687e2e8f9b2.png)

**Comment by ymuichiro** [comment]
マルチシグウォレットでハーベストは可能か？について

https://twitter.com/faunsu19000/status/1541450349713977344?s=20&t=YiLiYVc5ARROq6ifvfr0kw
