### ISSUE TITLE
ドキュメントのライセンスを決める

### ISSUE THREAD

**Issue by ounziw** [ymuichiro/symbol_japan_forum#12]
### 提案
ドキュメントのライセンスを決める

[Symbolの紹介文を用意しませんか](https://github.com/ymuichiro/symbol_japan_forum/issues/1)、の紹介文等を利用する場合のルールを決めたい。

参考：Wikipedia の場合は、[https://ja.wikipedia.org/wiki/Wikipedia:%E3%82%A6%E3%82%A3%E3%82%AD%E3%83%9A%E3%83%87%E3%82%A3%E3%82%A2%E3%82%92%E4%BA%8C%E6%AC%A1%E5%88%A9%E7%94%A8%E3%81%99%E3%82%8B](https://ja.wikipedia.org/wiki/Wikipedia:%E3%82%A6%E3%82%A3%E3%82%AD%E3%83%9A%E3%83%87%E3%82%A3%E3%82%A2%E3%82%92%E4%BA%8C%E6%AC%A1%E5%88%A9%E7%94%A8%E3%81%99%E3%82%8B)

**Comment by ounziw** [comment]
私個人は、Wikipediaと同じルールで良いと考えています。

1. 独自にルールを決めるのは大変
2. Wikipediaなら、多くの人が知っているので、Wikipediaと同じルールなら、詳しい説明しなくても理解されやすい

**Comment by ymuichiro** [comment]
@ounziw 
wikipedia のルール、一旦読んでみて以下の点、注意かなと思いました

1. テキストはクリエイティブ・コモンズ 表示-継承ライセンスの下で利用可能なこと
2. 1のため、紹介文利用時にライセンス条項を明確にしなければならない点
https://ja.wikipedia.org/wiki/Wikipedia:Text_of_Creative_Commons_Attribution-ShareAlike_3.0_Unported_License

ちょっと説明文貼るに対してこれを利用者に気にしてもらうのは面倒かなぁと。
ちなみに MITライセンス条項をちょっと書き換えるとこんな感じになるのですが、これだと緩すぎそうですか？

```
The MIT License
Copyright (c) <2022> <symbol_japan_forum>

以下に定める条件に従い、本文書の関連ファイル（以下「ファイル」）の複製を取得するすべての人に対し、ファイルを無制限に扱うことを無償で許可します。これには、ソフトウェアの複製を使用、複写、変更、結合、掲載、頒布、サブライセンス、および/または販売する権利、およびソフトウェアを提供する相手に同じことを許可する権利も無制限に含まれます。

上記の著作権表示および本許諾表示を、ファイルのすべての複製または重要な部分に記載するものとします。

ファイルは「現状のまま」で、明示であるか暗黙であるかを問わず、何らの保証もなく提供されます。ここでいう保証とは、商品性、特定の目的への適合性、および権利非侵害についての保証も含みますが、それに限定されるものではありません。 作者または著作権者は、契約行為、不法行為、またはそれ以外であろうと、ファイルに起因または関連し、あるいはファイルの使用またはその他の扱いによって生じる一切の請求、損害、その他の義務について何らの責任も負わないものとします。
```
https://licenses.opensource.jp/

**Comment by ounziw** [comment]
私の考えとしては、「出典（元がどこか）を表記する」は必要だとおもいますが、Wikipediaより緩くてもよいと思います。

ドキュメントだと、MITライセンスよりも、cc-by(クリエイティブコモンズ・表示)でしょうかね

**Comment by ounziw** [comment]
サンプルコードとか、有志作成のライブラリとかも、ここに置くなら、ドキュメントもコードもMITでも良いかも

**Comment by ymuichiro** [comment]
@ounziw 
ありがとうございます。
サンプルコードやソフトウェアは基本MITが良さそうですね

ちなみにロゴやドキュメントの方なのですが人ごとに事情によりCC0が選択できないケースがあるようなので、以下ディレクトリの通りフォルダ毎にライセンスを記載したファイルを設置してCCライセンスを参照するケースを取ってみました

こんな感じですかね
https://github.com/ymuichiro/symbol_japan_forum/tree/main/logo

MITライセンスは GitHub が提供してくれている形式があるので、以下をフォルダ毎に置く感じかなと
https://github.com/ymuichiro/symbol_japan_forum/blob/main/projects/LICENSE

**Comment by ounziw** [comment]
良いと思います。

ロゴのフォルダ↓に、クリエイティブコモンズへのリンクを載せておきましょう
https://github.com/ymuichiro/symbol_japan_forum/tree/main/logo

**Comment by ymuichiro** [comment]
@ounziw こんな感じですかね
https://github.com/ymuichiro/symbol_japan_forum/tree/main/logo

**Comment by ounziw** [comment]
ありがとうございます。
これで行きましょう
