### ISSUE TITLE
パイレーツアカデミー準備編　クラスター（法人・団体・個人）情報ください。

### ISSUE THREAD

**Issue by matsuno3** [ymuichiro/symbol_japan_forum#24]
**コチラは、Discode（すんぼる広場）とsymbol japan forum（じむはぶ）の情報をスムーズにつなぐ役割の為に設けました。**
また、遊び心がほしいので親しみを込めてパイレーツアカデミーと名付けました。
この名称はnem奈々さんにDiscord内でアイディアを出していただきました。
この場を借りて御礼申し上げます！

コチラのスレッドで一旦情報を収集したいと思います。

**内容はSymbolを使っている企業、団体、個人、Symbolに関わる活動をしている企業、団体、個人　Symbolに関わるサービス等を予定している企業、団体、個人が対象です。自推、他推問わず、重複も関係なく紹介ください。**

一旦集計したのち、アカデミーの名にふさわしいカテゴリーに再分配します。例えば、音楽室、資料室、書庫、研究室、開発室、音楽部、絵画同好会、ノード運営部（小等学部、中等学部、大学部）等にしていこうと思いますが、アイディアがあればそちらを優先的に採用したいと思います。

**こちらに情報を集めて、Discordのコアデブに情報を受け渡しより活動状況を俯瞰しやすくします。結果、目に触れる機会が増えるとおもいます。**

また、広報機能を準備中です。イベント、企業紹介、活動紹介等定期的にTwitterで呟けるようにする予定です（交渉中）

**Comment by matsuno3** [comment]
https://nemlog.nem.social/ ネムログ

**Comment by matsuno3** [comment]
https://quest-bc.com/　QUSEST 目標を作成し、応援XYMもらいながらタテ化計画を実行するサービス

**Comment by matsuno3** [comment]
https://nemlog.nem.social/blog/76237　YUTOさんSyｍbol日報

**Comment by matsuno3** [comment]
https://nemgraph.net/ 写真投稿サイト　NEMが投げられるネムグラフ

**Comment by matsuno3** [comment]
https://twitter.com/Otakudes333　Symbol　COMSAコミュニティ　Twitterのコミュニティ

**Comment by matsuno3** [comment]
https://twitter.com/Otakudes333
SymbolCOMSAコミュニティーの人

**Comment by matsuno3** [comment]
https://twitter.com/symboljp_forum
シンボルジャパンフォーラム広報機能
情報呟くサービス

**Comment by matsuno3** [comment]
https://twitter.com/D_laplace666　
メタバースでSymbol活動している人
週間しんぼる運営者

**Comment by matsuno3** [comment]
ノード運営している人　たくさん

**Comment by matsuno3** [comment]
https://nemedia.jp/xymsettlement/
Symbol決済店達

**Comment by matsuno3** [comment]
https://twitter.com/xym_symbol
ノード運営でルーレットとか楽しいことやっている人

**Comment by matsuno3** [comment]
https://twitter.com/nabe387690473/status/1517874845786472448
翻訳BOT作っている人

**Comment by matsuno3** [comment]
https://twitter.com/essan_symbol
歩くとXYMもらえるネムツアやっている人

**Comment by matsuno3** [comment]
https://twitter.com/DANPA62270526
すんぼるすんぼるの人

**Comment by mikunNEM** [comment]
https://nemtus.com 
NEM / Symbol の技術の普及や発展を促進するNPO法人

**Comment by mikunNEM** [comment]
https://discord.com/invite/F5DQjgHBGw
nem Japan UserGroup 
NIS1 / Symbolのサーバ運用・アプリ開発に関する情報共有を目的とした、誰でも参加・発言可能なコミュニティ

**Comment by mikunNEM** [comment]
https://tanuson.slack.com/join/shared_invite/zt-jk7o1w5u-8oF2RkkgBpH~J2RSLddWyA
Tanuson Slack
ノード運営の神々が集う場所

**Comment by matsuno3** [comment]
https://twitter.com/pasomi_3
ぱそ美の人　ファンクラブでもつくるかー

**Comment by matsuno3** [comment]
http://tezukalab.private.coocan.jp/shizuilab/
「すべての人に再生医療を届ける」という目的のために、細胞のトレーサビリティにSymbol/dHealthブロックチェーンを使う事業。岐阜大学の親知らず由来歯髄細胞研究プロジェクトがもとになっている。
担当　https://twitter.com/habingofit

**Comment by matsuno3** [comment]
https://twitter.com/monakaJP?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1518229527591534592%7Ctwgr%5E%7Ctwcon%5Es1_&ref_url=https%3A%2F%2Fnemlog.nem.social%2Fblog%2F76257
Symbolのコピーチェーン作っている人

**Comment by matsuno3** [comment]
https://twitter.com/AI27982784
Symbol決済店情報まとめている人

**Comment by nononon00** [comment]
自推ですが、オプチャ、現在700名集まっているので
『分散型サポートセンター』として機能させていければと思ってます🙌
https://twitter.com/_nononon__/status/1376552922880729089?t=0YX7Bv2NYIYCbeMIWGN6LA&s=19

**Comment by matsuno3** [comment]
[https://twitter.com/ahikicoin/status/1519332721222250497](https://twitter.com/ahikicoin/status/1519332721222250497)
ノード運営まとめている人

**Comment by matsuno3** [comment]
https://twitter.com/umesetu2011/status/1519894945553055744
レーサーの人

**Comment by matsuno3** [comment]
https://hackathon-2022.nemtus.com/works/
ハッカソンのゲーム一覧

**Comment by matsuno3** [comment]
https://twitter.com/taikoozisan/status/1520017934034239488
シンボル決済のお店をGoogleマップ化した人

**Comment by matsuno3** [comment]
https://twitter.com/ishidad2/status/1522501127433953281
XEMBOOK復刻版
（NEM）運営している人

**Comment by matsuno3** [comment]
https://twitter.com/cryptcoin001/status/1521909358925590528
NFTーDEXマニュアル

**Comment by YUTOpian** [comment]
このリンク集は役に立つと思っています。
https://nemlog.nem.social/blog/58308

**Comment by YUTOpian** [comment]
また、このリンク集の作成にも役に立つかと思っています。
https://github.com/ymuichiro/symbol_japan_forum/tree/main/links

**Comment by matsuno3** [comment]
https://twitter.com/horaemom/status/1527657788578492417
NFT座談会（メタバースcluster)の人

**Comment by matsuno3** [comment]
https://nemxym.com/xym%e6%b1%ba%e6%b8%88/
SYmbolプラットフォームを作っている人

**Comment by matsuno3** [comment]
https://symbol.openapostille.com/
オープンアポスティーユ

**Comment by matsuno3** [comment]
https://qiita.com/nem_takanobu/items/ec9c24e0dfd43d84e1d2
Rustを使ってSymbolブロックチェーンのトランザクションを送信する

**Comment by matsuno3** [comment]
https://qiita.com/nem_takanobu/items/d69f86487fce527dbc29
自分の得意なプログラミング言語でSymbolブロックチェーンを動かす方法

**Comment by matsuno3** [comment]
https://qiita.com/nem_takanobu/items/09b6b687f3cbe10af945
自分の得意なプログラミング言語でSymbolブロックチェーンを動かす方法

**Comment by matsuno3** [comment]
https://www.youtube.com/watch?v=nYXFC9f1_Jo&list=PLifx63Bv-tdNXe3DqVQtqphIbGm2Ikl3a&ab_channel=%E6%9D%BE%E6%9C%AC%E4%B8%80%E5%B0%86
速習 [#symbol](https://twitter.com/hashtag/symbol?src=hashtag_click) の再生リストです
