### ISSUE TITLE
お仕事掲示板 - 対応者求む

### ISSUE THREAD

**Issue by ymuichiro** [ymuichiro/symbol_japan_forum#25]
コミュニティの活動やSymbol界隈で生まれた誰かがやるべきであるタスクを記載するトピックとなります
もしSymbolの活性に向けて何かやってみたい、もしくは自身でQuest等での懸賞金獲得による収益化を狙い、ここに掲載されるお仕事を対応頂けないでしょうか

もし、やり方がわからない際には、ふぁーまで連絡ください
https://twitter.com/faunsu19000

**Comment by ymuichiro** [comment]
#19 [リクエスト］Twitterアーカイブサービス

TwitterやNEM Forumのデータを htmlやmd形式に変換し、誰もが参照できる状態にするタスクが発生しました
どなたか対応できる方は #19 にて対応を行なってください

**Comment by ymuichiro** [comment]
Qiita、NEMLOG ⇄ Discord連携チャンネルの開発

https://discord.com/channels/856325968096133191/864548768249544704/967699257844965397
上記スレッドの通り簡単な連携システムを開発する

**Comment by 0x6861746366574** [comment]
今週開設する採用情報ページのヘッダー画像を、@yasudagabou、@rookbl、@mahorobart、@jinjiroXYMの作品をモデルに、コミュニティの楽しさやワクワク感を表現したイラストで制作していただける方を募集しています。この採用情報ページは、NEMとSymbolの両方を対象としています。寸法は横1500px、縦500pxです。

クエストボードやジョブボードが画像に含まれていることが受賞の条件となります。[For example](https://assetstore.unity.com/packages/3d/environments/fantasy/quest-board-150950): 
![image](https://user-images.githubusercontent.com/71042900/166155422-2773a74d-9dab-40ac-949c-243f16e9c3d8.png)

5名の受賞者を決定します。

`当選者#1`：3000XYM
`当選者#2`: 2000 XYM
`当選者#3〜5` 1000 XYM

**Comment by ymuichiro** [comment]
イラストの投稿ルームを用意しました。
現時点ではまだ投稿者はいないので、応募希望の方はどんどん投稿していきましょう！
ーー＞ https://github.com/ymuichiro/symbol_japan_forum/discussions/32#discussioncomment-2678250

**Comment by matsuno3** [comment]
担当：ゆるてぃ公爵さん(https://twitter.com/ulty_investor)
編集に協力いただける方を急募！
誰でも編集可能ですが、良識&知識豊富な方に一定の権限付与をしようと思ってます！
手伝ってもいいよという方はお声がけください！
[https://twitter.com/ulty_investor/status/1522889932012138497](https://twitter.com/ulty_investor/status/1522889932012138497)
[#NEM](https://twitter.com/hashtag/NEM?src=hashtag_click) [#Symbol](https://twitter.com/hashtag/Symbol?src=hashtag_click) [#XEM](https://twitter.com/hashtag/XEM?src=hashtag_click) [#XYM](https://twitter.com/hashtag/XYM?src=hashtag_click)

NEMwiki

**Comment by matsuno3** [comment]
担当：ENAKOさん　https://twitter.com/cryptcoin001

NFT-Driveのパブリック版等の広報お手伝いさん募集です！
https://twitter.com/cryptcoin001/status/1522887372060639235
手を上げてくれる方いると良いですね！
手伝ってくれる方は公認アンバサダーに認定‼️？？かも？
２０２２年５月７日掲載

**Comment by ENAKO0516** [comment]
> 担当：ENAKOさん　https://twitter.com/cryptcoin001
> NFT-Driveのパブリック版等の広報お手伝いさん募集です！ https://twitter.com/cryptcoin001/status/1522887372060639235 手を上げてくれる方いると良いですね！ 手伝ってくれる方は公認アンバサダーに認定‼️？？かも？ ２０２２年５月７日掲載

matsunokiさんありがとうございます。

【補足します】
NFT-Driveチームがより一層、企業向けにPRしていく時間を割くために、お手伝いを募集します。
内容としては、NFT-Driveパブリック版のみの対応に限定し、コミュニティ内外への広報や、NFT-Driveを利用する際の問い合わせや手順書の整備などのお手伝いさんを募集いたします。
報酬はありませんが、Web3の考え方や、最先端の経験値が得られるのはメリットかもしれません。
あと、NFT-Drive公認アンバサダーに認定し、認定書をフルオンチェーンＦＴとして発行し、お渡しします。

**Comment by ymuichiro** [comment]
## お仕事募集

Symbol 公式風サイトにおける
Symbol の特徴紹介作成ページへの協力、支援

## 必要なスキル

- DeepL を使ってSymbol のホワイトペーパーを読んだり ハチェットさんへ質問できる事
- Google document に文字入力が出来るスキル

## 報酬
- 貢献度合いに応じて 適宜以下アドレスに溜まったハーベスト報酬より払い出されます

> NAXSH7VBPXFR6UEILARG46AXP4HTEJXZ5D44F4Q

- 貢献度の錯視定規的基準は定めていません。明確化を求める場合は事前に協議をしてから作業を行なって頂きます
- ハーベスト報酬の実入により払い出し可能な Symbol の枚数は可変します
- 一般的な社会的活動の報酬額に対しては低くなります。金銭目的だけでの参加の場合、辛くなる可能性があります

## 作業内容（例

- Symbol のホワイトペーパー読み込み
- 特徴の精査、書き出し
- Blockchain開発側への質問によるすり合わせ
- 公開に向けた清書

## 得られるもの

- Symbol に対するより正しい知識、並びに技術的な知識
