### ISSUE TITLE
教育機関向けの教材をコミュニティで作りませんか？

### ISSUE THREAD

**Issue by ymuichiro** [ymuichiro/symbol_japan_forum#26]
Twitter上で以下のような投稿がありました
Symbolは私としてはブロックチェーンの教材に向いていると思います
https://twitter.com/nrq_jp/status/1518928239145590786?s=20&t=wJBvlaaw7JAKwvOZYEQZGw

POINT
1. Symbolは入門し易いJavascriptで記述可能
2. テストノードが比較的簡単に建てられる or コミュニティのノードも使える
3. アカウント作成や送金といった処理も簡単にできる

何か教育機関で使ってもらえそうなコンテンツを決めて教材を作ってみるのはどうでしょうか
ご意見、アイディア、私一緒に作るぞ等、もしコメントあれば書いてもらえると嬉しいです

ちなみに個人的な感覚として教育内容は文部科学省の学習指導要領に沿う必要があると思っていますので
あまりそれを無視したコンテンツは使われないだろうとは踏んでいます
https://www.mext.go.jp/a_menu/shotou/new-cs/1384661.htm

**Comment by kanekodaisuk** [comment]
実は僕は前職『小学生向けプログラミング教室』の教室長兼講師でした。
教材はマイクラ。
そんな僕として言えるのは小学校で導入されている『プログラミングを用いた授業』はプログラミングそのものの習得を目指していません。
学ぶのは『論理的思考』です。
プログラミングをする際にプログラマーが『作りたいもの(目標)』を決め、コードを打ち込み(行動)、実際に動かして『不具合はないか(修正)』『より良くできないか(改善)』を考え、またコードを打つを繰り返す(試行錯誤をする)というのが論理的思考を養うのでプログラミングを教材に選ばれたという経緯があります(日本にかぎらず海外でも同じ理由です)。

なので、Symbolというブロックチェーンでのプログラミングを通して論理思考を学習する方針で考えたほうがいいと思います。

Symbolで教材を作るだけではなく、Symbolを教材にプログラマー的思考力(論理思考力)を身につけられるカリキュラムを用意するというのも教育機関へのアプローチには有効とも。

ちなみに僕はプログラミングできませんが😅

**Comment by YUTOpian** [comment]
教材作成に関して、参考資料にできれば・・・
https://nemlog.nem.social/blog/56258

**Comment by mikunNEM** [comment]
XEMBookさんが神記事を公開してくれました🥳

https://twitter.com/xembook/status/1519156867473174528

https://github.com/xembook/quick_learning_symbol

**Comment by matsuno3** [comment]
https://nemlog.nem.social/blog/76347
タイムリーにニーズが生まれたので、これを軸に進めていけばよさそうですね。

**Comment by matsuno3** [comment]
https://nemlog.nem.social/blog/56258
そういえばしゅうさんに超入門の講師してもらったんだった。まだ使えるからご参考までに。

**Comment by trestoJP** [comment]
作る人のための教育教材と使う人のための教育教材を分けるといいと思います。
作る人はまず使う立場のことも学ぶ必要ありますが、作らず使う人は作る人のための教育はなくてもいいので。

**Comment by kanekodaisuk** [comment]
小学生向けプログラミングツールとしては『スクラッチ』というのがあります。
ブロックパーツを組み合わせて色々できるツールで、中身はJavascript。

https://scratch.mit.edu/studios/1168062

あと自分が教室で使ってたのはマイクラでプログラミングする『Make code』で、こちらもJavascript。

https://dekiru.net/article/18672/
↑Make codeのページではありませんが説明されてるので。

こんな感じでプログラミングできたら子供もとっつきやすいかも。

特にマイクラと組み合わせられるなら……僕でもできそうです😆

**Comment by ymuichiro** [comment]
@kanekodaisuk ちょっと冗長になるかもしれないけど、MakeCodeに Token 送信、 Token 確認、みたいなカスタムブロックは作れそうね

Javascriptでかける行数に制限があったら手こずりそうだけど。

https://inosyan.hateblo.jp/entry/2018/10/17/003606

**Comment by kanekodaisuk** [comment]
技術的なことは分かりませんが、MakeCodeみたいにブロックを組み立てるみたいにプログラミングできたら老若男女関係なくできそうかな？と。

2022年5月21日(土) 13:24 ふぁー ***@***.***>:
