### ISSUE TITLE
【試運転開始】Symbol & NEM Community Info申請所

### ISSUE THREAD

**Issue by matsuno3** [ymuichiro/symbol_japan_forum#27]
こちらは新しくできたSymbol & NEM Community Info申請所です。
[Symbol & NEM Community Info](https://twitter.com/symnem_com_info)

【８月１日更新予定】
下記の手順・ルールにより広報に使用することができます。

Symbolに関連する配信したい情報。（計画、実行、運営、達成したこと、企画募集、アンケートなど）
（コミュニティアンケート結果により　ノード運営情報　解禁）

【ツイート内容】
・tweet申請した者のアカウント（自己申し込み、他推申し込み可能です）
・広報文
（・募集、紹介、お尋ね等・内容先リンク等）
※法律に触れる文面、サービス案内等は禁止します

【手順・スケジュール】
１・申請所スレッドにコメントで情報をお書きください。
【暫定ルール】随時tweetされます。

下記ルールは運営開始後込み合ってきたときに適用します。
【２・不正防止、内容確認の為３日間スレッドで誰でも閲覧できる状態で情報が公開されます。】
【３・４日以降７日以内にtweetされます。日にち指定、時間指定はできません。】

【トラブル発生時の対応】
トラブル発生確認後、活動を停止します。
活動再開は、原因特定、原因対策、コミュニティーアンケート等でコンセンサスを取った後、再開されます。

【免責事項】
ツイート内容によるトラブルは申請者が責任を負います。
他推の場合のトラブルに関しても申請者が責任を負います。
こちらの機能はあくまでも広報窓口であり、他の機能を有しません。

運営方針
コミュニティーファースト

行動指針
・助けられる範囲で助けあいます。
・教えられる範囲で教えあいます。
・活動している人を応援しあいます。

活動内容
・広報力の弱い人の補助を行い、隠れた有益な情報を発信します。
　じむはぶに窓口を設け広報tweetする内容を募集します。
　※運営者も指定された手順に従い広報します。
・直接価格に関係するような一次情報は取り扱いません。

**Comment by matsuno3** [comment]
Arcanaでgiveaway用絵付きモザイク（トークン）を作ろう
https://nemlog.nem.social/blog/75382
投稿者　matsunoki

**Comment by hossiiii** [comment]
こんな感じで申請大丈夫でしょうか？？

【TokenLive】
特定のトークンを持った人だけが参加できる限定ライブ配信サービス。
投げ銭（xym）手数料なし！

NFTアーティスト⇄購入者
ノード運営者⇄委任者
その他様々な関係性の向上にお使い下さい！

https://tokenlive.me/
投稿者　hossiiii1

**Comment by mikunNEM** [comment]
ありがとうございます。
画像とか何か良さそうなものはありますか？
何か添付するとより効果的かなと思います。

**Comment by hossiiii** [comment]
はっ！画像追加します！

**Comment by matsuno3** [comment]
こんなかんじ？

**Comment by mikunNEM** [comment]
良いと思います👍
画像を添付してツイートしましょう。

**Comment by matsuno3** [comment]
呟いたらやり取りは消しますねー　hossiiiiさんこれでいいですか？

**Comment by hossiiii** [comment]
遅くなってすみません
添削もありがとうございます
すごくわかりやすくなっていますね。
助かりました
こちらでよろしくお願いいたします！

**Comment by matsuno3** [comment]
YUTO氏Symbol日報試運転開始しました。１日目
https://nemlog.nem.social/blog/76643

**Comment by matsuno3** [comment]
【ヴォーノ氏企画紹介】思いっきり描いてください！NFT出品手数料負担します！（COMSA)
https://nemlog.nem.social/blog/76635
（予算5万xym位）参加方法は５月１９日夜～２０日２３時５９分の間に固定されたtweetに対してリプで褒めまくる。
https://twitter.com/usotukijinrou/status/1526129140663205888
#絵師 #NFT #お絵描きさんと遊びたい ＃Symbol

**Comment by nononon00** [comment]
気軽に質問できる場所として、LINEオープンチャット「Symbol×NEM 初心者歓迎🔰質問・情報共有」が開設されています。

わからないこと、わかること、トラブル等の共有にご利用ください🙌

📣趣旨
https://nemlog.nem.social/blog/59210

📣利用方法、ルールとお願い
https://nemlog.nem.social/blog/71861


お邪魔します！
こんなかんじですかね？🤔

**Comment by USB2021** [comment]
ホラえもん　@horaemom です。申請をさせていただきます。申請があることを教えていただきましてありがとうございました。よろしくお願いいたします。
詳しい内容も決まっていませんが、根底のルールはどんどんルールを決めていく方が、たぶん皆さん楽なんじゃないかと思っています。そこで意見があれば検討しかえたりします。今回の告知はクリエイターの方々に気楽に都合よく参加してもらいたいという思いをイメージやユースケースを感じ取ってもらえたらと思って、極力堅い雰囲気とルールは除外しました。私も本格運営はできないので、皆さんにこういう交流があったら如何でしょうかという提案のつもりです。
今後説明にあるテンプレートも考えてネムログで伝えます。乗り気の方が出たら一緒に始めてみようかなと思いますが、私も始めてみてツイートでその結果も報告してこうと思います。
告知をしてしばらくしても利用がければ必要が無いということで活動もやめて深追いの宣伝はやめます。サイレントマジョリティになりがちなクリエイターの方々の交流の為にもよろしくお願いいたします

それでは以下の文章で申請させていただきます。


@horaemom
nemlogでNFTクリエイター COMSAエンドーサー コレクターの方々が
cluster上で誰でも雑談会を開く方法を検討しています。
気軽に、好きな時開催参加が前提です。NEMLOGの詳細をご覧ください。
アイデアや要望。ハッシュタグも募集中。私の固定ツイートで返信もOKです
https://nemlog.nem.social/blog/76644
![image](https://user-images.githubusercontent.com/79322460/168832142-3d60ea13-b469-4a98-9d6e-239a32a3f4a3.png)
![image](https://user-images.githubusercontent.com/79322460/168832217-ea393f8a-c049-4793-9178-49006d85cb44.png)
![image](https://user-images.githubusercontent.com/79322460/168832245-a45ec048-b47b-4314-b169-b7f95557f692.png)
![image](https://user-images.githubusercontent.com/79322460/168832283-bf20d361-497e-4dcb-97d3-8c88fe8af92d.png)

**Comment by mikunNEM** [comment]
ホラえもんさん、こんな感じでどうでしょうか？

---------------------------

nemlogで、NFTクリエイター、COMSAエンドーサー、コレクターの方々がCluster上で誰でも雑談会を開く方法を検討しています。
アイデアや要望。ハッシュタグも募集中。
詳しくはこちらをご覧ください。
➡️https://nemlog.nem.social/blog/76644

お問い合わせは @horaemom  までお願いします。
#Symbol #COMSA #NFT

**Comment by USB2021** [comment]
とっても読みやすくしていただいて、どうもありがとうございます！
こちらでよろしくお願いいたします

**Comment by mikunNEM** [comment]
ではこちらをツイートしますね😊

**Comment by mikunNEM** [comment]
テスト

**Comment by matsuno3** [comment]
【nemlogイベント紹介】
AndroidまたはChrome Bookのみ
NEMをベースにした落ちものパズルゲーム「MATCHnem」のスコアアタック大会２２日迄開催中です！
賞金はスコア上位10人に対して100XEMを山分けをします
詳しくはコチラ　投稿者mmatsunoki 主催者YUTO氏
https://nemlog.nem.social/blog/76132
![16500678972018_insert_image_000220のコピー](https://user-images.githubusercontent.com/47351682/169247143-743dbf21-a01e-4090-a91b-19ee03735988.jpg)
。

**Comment by mikunNEM** [comment]
アプリ開発者の皆さんへご紹介です💻

「NEM Japan UserGroup」 は、Symbolコミュニティの日本の開発者が集まるDiscordです。

Symbolブロックチェーンを使ったアプリ開発を検討されている方は是非ご参加ください💁‍♀️

➡️https://discord.gg/F5DQjgHBGw

#Symbol #XYM #ブロックチェーン #dApps
![FSfN45XVsAESAMl](https://user-images.githubusercontent.com/45915246/169294938-d88b2b7b-3301-4af5-9ca0-c59bf2415288.jpeg)

**Comment by matsuno3** [comment]
【ヴォーノ氏企画再告知】思いっきり描いてください！NFT出品手数料負担します！（COMSA)
https://nemlog.nem.social/blog/76635
参加方法は本日２０日２３時５９分の間に下記の固定ツイートにリプで褒めまくる。
https://twitter.com/usotukijinrou/status/1527184062867439616
なお、絵の出品自体は出来次第でいいらしい（１０年後もあり？）
#絵師 #NFT #お絵描きさんと遊びたい ＃Symbol

**Comment by matsuno3** [comment]
週末はイベントでもいかが？
私はD&Dキャンペーンなどの創作ライターですが、
これらの回答を集めて「宇宙での」歴史を書くことに興味を持ちました。
【総額１０００XYM】教えて？あなたのリアルなXYM（NEM）活歴史話
https://nemlog.nem.social/blog/76447

**Comment by matsuno3** [comment]
【お題イベント情報５００XYM】
https://nemlog.nem.social/blog/76680
Symbol・NEMで実現したい未来
というお題を5月末まで開催しています。
主催者　だい　広報者 matsunoki
![スクリーンショット 2022-05-20 193419](https://user-images.githubusercontent.com/47351682/169510578-12ff0e6d-9bf6-4087-a0f7-b6b54dc007ab.png)

**Comment by matsuno3** [comment]
@horaemom
https://twitter.com/i/communities/1527485626429239297
[#NFT座談会](https://twitter.com/hashtag/NFT%E5%BA%A7%E8%AB%87%E4%BC%9A?src=hashtag_click)　を作りました。コミュニティのメンバー登録をお願いいたします。（会員とかではありません）　簡単に告知いただける為のテンプレとルール置き場や、アンケートの結果報告などします。また皆さんの告知、要望などにも利用下さい。　[#symbol](https://twitter.com/hashtag/symbol?src=hashtag_click) [#comsa](https://twitter.com/hashtag/comsa?src=hashtag_click) [#HEXA](https://twitter.com/hashtag/HEXA?src=hashtag_click)

**Comment by mikunNEM** [comment]
Symbol Discord には、NFT-Drive の専用チャンネルがあります。
開発者ボー太郎博士さんの投稿を見る事やコメントも出来ますので是非遊びにきてください💁‍♀️

NFT-Drive  ウェブサイト
https://www.nft-drive.com

Symbol Discordの始め方
https://nemedia.jp/symboldiscordlogin/

#Symbol #XYM #NFTDrive

<img width="1292" alt="スクリーンショット 2022-05-21 12 28 38" src="https://user-images.githubusercontent.com/45915246/169634018-9a3cc85f-fbac-42c0-8b30-b156e103c06a.png">
<img width="993" alt="スクリーンショット 2022-05-21 12 24 06" src="https://user-images.githubusercontent.com/45915246/169634025-c11f4cd7-ef10-4aae-b734-ba442a539b06.png">

**Comment by cafe22** [comment]
【ツイート内容】@22CAF1
以前公開した、加盟店共通ポイント構想ですが、遂に金融庁から許可が出ました🙌
来週25日から、サンドイッチ・ファクトリーさん
@sandwichf1　芝浦田町スポーツ整骨院・はり治療院さん@irifuneshinmori
 と運用開始です🙌
詳細はhttps://nemlog.nem.social/blog/76659 にてご確認ください。

#XYM #symbol #モザイク

**Comment by mikunNEM** [comment]
ちょっと文字数の関係で編集させてもらいました🙏

以前公開した、加盟店共通ポイント構想ですが、遂に金融庁から許可が出ました🙌
 来週25日から、サンドイッチ・ファクトリーさん@sandwichf1芝浦田町スポーツ整骨院・はり治療院さん@irifuneshinmori で運用開始です🙌
 詳細はこちらへ➡️https://nemlog.nem.social/blog/76659 

#XYM #symbol #モザイク @22CAF1

**Comment by cafe22** [comment]
mikunさん

早速チェックして頂きありがとうございます！
どうぞよろしくお願いいたします！

米倉

2022年5月21日(土) 18:41 mikun ***@***.***>:

**Comment by matsuno3** [comment]
【イベント情報】https://urlzs.com/YZhiJ
ハルコメ × ESSANコラボイベント ＝ 『ESSAN塗り絵コンテスト』開催中です！詳しくは↓
https://urlzs.com/zBW66
ルール
①
[@pai3art](https://twitter.com/pai3art),[@essan_symbol](https://twitter.com/essan_symbol)
 をフォロー
②添付イラストを色塗り
③リプで応募
④みんなのいいね1点RT2点で採点
⑤締切:5/29

賞金
1位3000円
2位2000円
3位1000円

上記金額相当の [#XYM](https://twitter.com/hashtag/XYM?src=hashtag_click),[#アマギフ](https://twitter.com/hashtag/%E3%82%A2%E3%83%9E%E3%82%AE%E3%83%95?src=hashtag_click),[#HEXANFT](https://twitter.com/hashtag/HEXANFT?src=hashtag_click)(
[@HEXANFT](https://twitter.com/HEXANFT)
)
![FTLBQUeVEAAa3iW](https://user-images.githubusercontent.com/47351682/169646747-dfdc36fe-7451-4e0e-9c6a-eaf755460266.jpg)
![FTLBQUfUsAE3SiS](https://user-images.githubusercontent.com/47351682/169646749-13e76625-afab-4165-a34a-ddb2be729ed9.jpg)

**Comment by matsuno3** [comment]
ブロックチェーンデータの資源化活動
#codewill 始めます。
https://nemlog.nem.social/blog/76708
フルオンチェーン等で恒久的に残っていくデータを資源と見立て
生活の一部に取り入れていこうという活動です。

**Comment by matsuno3** [comment]
【速報】【Symbol公式声明】
https://twitter.com/0x6861746366574/status/1528184971474522113
https://twitter.com/0x6861746366574/status/1528168089442865152
法律や税金の問題で日本で[#Symbol](https://twitter.com/hashtag/Symbol?src=hashtag_click)に製品を発売できないと思っているすべての人に、製品を作成してからお問い合わせください。私たちはあなたがそれを立ち上げるのを手伝います。
プロトコルの構築は、私たち全員のパートナーシップです。

**Comment by koooo0** [comment]
#COMSA #NFT #Symbol 
【メンヘラ速報】
#メンヘラ少女ダイリちゃん の新しい作品が公開されました！

「私と友達になって」

ヨワイちゃんの放った一言に対して、ダイリちゃんはどう応えるのか！？

↓詳細はCOMSAの作品ページをチェックしてください！↓
https://comsa.io/nft/ee357cf1-067c-48b0-b7dd-b1c953bfb559

![名称未設定 2](https://user-images.githubusercontent.com/103552124/169697132-bc817131-b27a-432b-9e5c-08ec56c0b86e.png)

**Comment by matsuno3** [comment]
#Symbol エスクローコントラクト
（第三者を介しない売り手と買い手の同時取引アルゴリズム）
のデモンストレーション。これから学びたい人や詳しく知りたい人は見るだけでも価値があるよ？
https://www.youtube.com/watch?v=ffvtpiijWds&ab_channel=%E6%9D%BE%E6%9C%AC%E4%B8%80%E5%B0%86
作成者 [@kazumasamatsumo](https://twitter.com/kazumasamatsumo)　[松本一将](https://www.youtube.com/channel/UCdUPFdF9vvS6TMdXChr7rvg)　広報者matsunoki

**Comment by mikunNEM** [comment]
ストレスが溜まった時に押すボタンの紹介です🚨

気が済むまでボタンを押してみてください💁‍♀️
➡️https://d39v8uj7qnz25w.cloudfront.net/tab1

このアドレスを知る人が、どの日にストレスを感じることが多いのか？が分かります。

#Symbol のメインネットを使用しています。

開発者: @kazumasamatsumo   広報者: mikun
<img width="539" alt="スクリーンショット 2022-05-25 23 54 25" src="https://user-images.githubusercontent.com/45915246/170299736-12fad5fd-4235-42c7-845b-4c43453c8dcf.png">

**Comment by ishidad2** [comment]
#SORACOM LTE-M Button PlusのクリックデータをSORACOM Beam と #NodeJS を使って #ブロックチェーン に記録したお話です。
ブロックチェーンはJSで手軽に扱える#Symbolを採用。

IoT×ブロックチェーンの記事です。ぜひご一読ください。

https://qiita.com/ishidad2/items/3f2d4a12616c5fb80120

執筆者: @ishidad2

**Comment by matsuno3** [comment]
#Symbol　VALKYRIE公認デザインをした車🏎️でおなじみ梅さん(梅村設備)
@umesetu2011　さんが出場します！

【[#B2eLEAGUE](https://twitter.com/hashtag/B2eLEAGUE?src=hashtag_click) SEASON1 -round1-】
明日5/29(日)12時開幕！
第1回大会「[#GTSPORT](https://twitter.com/hashtag/GTSPORT?src=hashtag_click) 」「[#プロスピA](https://twitter.com/hashtag/%E3%83%97%E3%83%AD%E3%82%B9%E3%83%94A?src=hashtag_click)」
社会人プレイヤーの熱い対戦をお見逃しなく！
皆さま参戦並びに応援、宜しくお願いいたします。

👇配信URL
https://youtube.com/watch?v=LAMsczAFsEA

**Comment by nononon00** [comment]
ちょっと長いですが…リプへ含めた2ツイート可能でしょうか？
よろしくお願いいたします🙏

----------

チャリティーアートフェスティバル
『モザワン2』開催

■公式サイト
https://t.co/rtBhXRcUL6

■募集作品テーマ
『Peace』

■作品募集期間
5/28～6/25

ウクライナの平穏を願う全ての方が参加いただけます。


------


モザワンに国境はありません。

  国境を持たない『アート』
  国境を持たない『技術』
  国境を持たない『お金』

これらを融合させ、最大限活用することで、皆様の想いを乗せた支援金を、ウクライナへ直接届けます。

■公式Twitterアカウント
https://twitter.com/mosaic1gp_2

**Comment by matsuno3** [comment]
【important mission】
https://onl.sc/2zcQZU6
ごきげんよう、#Symbol の皆さん。さて、今回の指令だがSymbolのコアデベロッパーの一人ハチェット氏が
#Arcana のモザイク図鑑を完成させるため秘密裏に活動ている。申し訳ないが、コンプリートするのは不可能だろうと思う。
しかし、成功に向かっているとき、失敗は必ず繰り返すもの。皆さんの協力が限りない成功に導くものと期待している。
あげていいモザイクを是非あげてほしい。健闘を祈る。なお、このメッセージは5秒後に自動的に消滅する。（しない）
https://twitter.com/0x6861746366574/status/1530628811997339648

**Comment by Banisty** [comment]
◎シンボル決済はじめました‼︎
　皆さんよろしくお願いします。

【塩cafe】
　福岡県直方市殿町12-23
　080-7981-3343

大正時代からある国登録有形文化財の建物を改装し、レトロcafeとしてオープン。
情緒あふれる歴史建造物でごゆっくりお過ごしください。

![019BD287-16B2-42C9-A5D0-B80350CE0544](https://user-images.githubusercontent.com/106494072/170914446-f5f0f7d6-932d-421b-84a6-7ca6749e568b.jpeg)

instagramアカウント
https://instagram.com/shiocafe_nogata?igshid=YmMyMTA2M2Y=

**Comment by matsuno3** [comment]
浜田聡の質問 参議院 財政金融委員会 2022年06月03日　DCJPYとJPYC、国防費の増額、国内の規制の数、所得制限、等
に＃Symbol　が登場しています。これは言葉のトリック等ではなく正真正銘ブロックチェーンSymbolのことを指します。
なぜなら、Twitter上で実際にやり取りを行いトークンを発行し、＃Arcana　を通してモザイク配布を行ったからです。
０：５５付近にご注目ください。
https://twitter.com/NA5GGYbQ9Nm0iLm/status/1532495180666142720
広報者 matsunoki

**Comment by matsuno3** [comment]
https://twitter.com/nftdrive_jp/status/1533106658066726912

NFT-Drive's English website is now available.
(NFT-Driveの英語サイトを公開しました。)

[URL]
https://nft-drive.com/en/home-en/index.html

[#Symbol](https://twitter.com/hashtag/Symbol?src=hashtag_click) [#XYM](https://twitter.com/hashtag/XYM?src=hashtag_click) [#NFTDrive](https://twitter.com/hashtag/NFTDrive?src=hashtag_click)

**Comment by matsuno3** [comment]
２２：００アナウンス予定
https://twitter.com/DJ_kooooo/status/1503007483006427141
【ご報告】
Unity初心者でもつくれちゃう #Cluster 専用個展マニュアル完成しましたー！！！！🎊🎉🎉
たくさんのNFTアーティストさん達に個展を開設して楽しんでいただきたいので、是非皆さんご活用ください！🙇‍♂️
https://nemlog.nem.social/blog/75488
広報者　matsunoki

**Comment by matsuno3** [comment]
８：００アナウンス予定
https://twitter.com/kurikou_XymCity/status/1532366313431396352

先日の投げXYMボタンの記事上げました。気に入ってもらえたらLGTMポチお願いします🙇‍♂️🙇‍♂️🙇‍♂️ 
https://qiita.com/kurikou_XymCity/items/b0836c11629256fd397d
[#Symbol](https://twitter.com/hashtag/Symbol?src=hashtag_click) [#Python](https://twitter.com/hashtag/Python?src=hashtag_click) [#IoT](https://twitter.com/hashtag/IoT?src=hashtag_click) [#Qiita](https://twitter.com/hashtag/Qiita?src=hashtag_click)
広報者　matsunoki

**Comment by matsuno3** [comment]
２３：００アナウンス予定
https://twitter.com/CMXEYM/status/1532321239032901636

ダサいと、カッコいい、どちらも包摂できる可能性がある中ではじめて多様性と柔軟性が確保されうる。
多様性と柔軟性の高さは、滅びないためのセキュリティになる。
#Symbol #nem 自由に使えるロゴ提案です。
広報者　matsunoki

**Comment by matsuno3** [comment]
８：００アナウンス予定
https://twitter.com/xembook/status/1519156867473174528

GW前に速習Symbolというドキュメントを公開しました
https://github.com/xembook/quick_learning_symbol

最初から読み進めることでSymbolを無理なく系統立てて学習できるように構成しています（ブラウザだけ必要です）。

改変自由・商用利用OKです。
みなさんのお知り合いのすべてのソフトウェア開発者にお知らせください。
広報者　matsunoki

**Comment by matsuno3** [comment]
[#COMSA](https://twitter.com/hashtag/COMSA?src=hashtag_click) [#えむはっく](https://twitter.com/hashtag/%E3%81%88%E3%82%80%E3%81%AF%E3%81%A3%E3%81%8F?src=hashtag_click) [#symbol](https://twitter.com/hashtag/symbol?src=hashtag_click) [#拡散希望](https://twitter.com/hashtag/%E6%8B%A1%E6%95%A3%E5%B8%8C%E6%9C%9B?src=hashtag_click)  
／
第二回 [#イラストコンテスト](https://twitter.com/hashtag/%E3%82%A4%E3%83%A9%E3%82%B9%E3%83%88%E3%82%B3%E3%83%B3%E3%83%86%E3%82%B9%E3%83%88?src=hashtag_click)🎨
7月9日(土)開催決定 🎉
＼

✨参加者も賞金がもらえる企画！
✨だれでも参加可能！
✨メタバース美術館に飾られるチャンス！

[#入札金額賞](https://twitter.com/hashtag/%E5%85%A5%E6%9C%AD%E9%87%91%E9%A1%8D%E8%B3%9E?src=hashtag_click)
[#いいね賞](https://twitter.com/hashtag/%E3%81%84%E3%81%84%E3%81%AD%E8%B3%9E?src=hashtag_click)
[#運いいね賞](https://twitter.com/hashtag/%E9%81%8B%E3%81%84%E3%81%84%E3%81%AD%E8%B3%9E?src=hashtag_click)
の3部門🌈
広報　matsunoki

**Comment by matsuno3** [comment]
[#えむはっく](https://twitter.com/hashtag/%E3%81%88%E3%82%80%E3%81%AF%E3%81%A3%E3%81%8F?src=hashtag_click)
[#ApexLedgends](https://twitter.com/hashtag/ApexLedgends?src=hashtag_click) [#めんへら杯](https://twitter.com/hashtag/%E3%82%81%E3%82%93%E3%81%B8%E3%82%89%E6%9D%AF?src=hashtag_click) 開催決定！
なんと！[#メタバース](https://twitter.com/hashtag/%E3%83%A1%E3%82%BF%E3%83%90%E3%83%BC%E3%82%B9?src=hashtag_click)([#cluster](https://twitter.com/hashtag/cluster?src=hashtag_click))を使用した会場で [#e](https://twitter.com/hashtag/e?src=hashtag_click)-sports を開催します！ヾ(´∀｀)ﾉ

応募期間：6月11日（土）～7月10日（日）
開催期間：7月16日（土）21時スタート

【詳細は後日】
[https://ablook.wordpress.com](https://t.co/95sKOEvy4X)

是非拡散をお願いしますー！

**Comment by matsuno3** [comment]
【新ロゴ塗り絵コンテストのお知らせ予告】
現在はNEMのロゴを使用していますが、広報用Twitterの顔となるアイコンを下記に決定する予定です。
#Symbol #nem #じむはぶ
コミュニティー色を出すためアレンジした物１点を決定し、最終決定アンケートをTwitterで行い本採用とする予定です。
募集期間：７月９日（土）～７月１６日（土）
投票期間：７月１７日（日）～７月２０日（水）
詳しくはコチラ
https://docs.google.com/document/d/1ndAU0Wqf2Az1oFo2JxviBO7q8rBxIraoUaRZHaKt3GA/edit

**Comment by matsuno3** [comment]
【Symbol歌って応援！】
「HappyHarvest」のカラオケ配信の設定完了！
JOYSOUNDで6月18日から選曲出来る予定です。
https://musicpost.joysound.com/music/musicId:150635
主催者：kei 　@Kei_cc_777
#ノド坂46 #Symbol

**Comment by mikunNEM** [comment]
【新アイコン_ぬりえコンテスト予告】

現在は公式NEMのロゴを使用していますが、広報用Twitterの顔となるアイコンをコンテストで決定します。

募集期間：６月１８日（土）～６月２５日（土）
（募集期間が6月に前倒しになりました）

https://bit.ly/3He0oFe

#Symbol #じむはぶ広報アイコン

**Comment by mikunNEM** [comment]
株式会社Opening Lineさんからのプレスリリースです。

「サイバーセキュリティ分野で大手のラック様と協業し、#ブロックチェーン の社会実装を加速させていきます💪 」

#Symbol のパブリックチェーンも活用されているとの事。 
今後が楽しみですね😊

広報者: mikun

https://prtimes.jp/main/html/rd/p/000000001.000097604.html

**Comment by matsuno3** [comment]
https://twitter.com/essan_symbol/status/1537055827596435457
https://twitter.com/6x9wnkODCQ58OLo/status/1537052757068087296
まりちさんえっさんコラボ企画です。[#xymの思い出](https://twitter.com/hashtag/xym%E3%81%AE%E6%80%9D%E3%81%84%E5%87%BA?src=hashtag_click)　[#ノード運営者の思い出](https://twitter.com/hashtag/%E3%83%8E%E3%83%BC%E3%83%89%E9%81%8B%E5%96%B6%E8%80%85%E3%81%AE%E6%80%9D%E3%81%84%E5%87%BA?src=hashtag_click)　　を付けて呟こう。詳しくは上記Twitterにて。
広報者　matsunoki ＃Symbol　素敵な呟きが多いよ？

**Comment by mikunNEM** [comment]
【新アイコン_ぬりえコンテスト開催】

じむはぶ広報 Twitter の顔となるアイコンをぬりえコンテストで決定します。

募集期間：６月１８日（土）～６月２５日（土）

詳細は ➡️bit.ly/3He0oFe

どしどしご応募ください💁‍♀️✨

#Symbol #じむはぶ広報アイコン

**Comment by matsuno3** [comment]
今日は佐賀県みやき町で　[#Symbol](https://twitter.com/hashtag/Symbol?src=hashtag_click) 決済ができるよ！ [https://miyakikankou.jp/main/6858.html](https://t.co/h3uBfqHoPI)　ブースは秀虹　さんです！
広報者　matsunoki

**Comment by mikunNEM** [comment]
トークンを #イーサリアム(ERC-721) 、データは #Symbol で生成された世界初の
ハイブリットフルオンチェーンNFT のオークションが #OpenSea にて行われます✨

皆さん是非ご参加ください☺️✨

広報者:mikun

https://twitter.com/nftdrive_jp/status/1540634559032983552?s=20&t=S_DdfSZaRDc7G3OVzg3BcQ

**Comment by mikunNEM** [comment]
Zaif Payment についてのアンケートを行なっています💁‍♀️

https://zaif.jp/payment

Zaif Payment で #XYM(#Symbol) が対応されれば、お客さんは XYM で支払いをして、お店側は日本円で受け取る事が出来るようになります✨

Zaif さんへみんなの声を届けましょう✨

広報者: mikun

**Comment by matsuno3** [comment]
８：００に予約しました。

**Comment by matsuno3** [comment]
github.com/ymuichiro/symbol_japan_forum/issues/27　広報窓口開始後約４５日経過しました。話し合いの中で暗号資産が今後低迷することを考え、できるだけノード運営者に生き残っていただくために９０日後解禁予定だったノード宣伝を可決後解禁することを　[#Symbol](https://twitter.com/hashtag/Symbol?src=hashtag_click)

**Comment by matsuno3** [comment]
【じむはぶ取材班matsunoki】じむはぶ本運転の試験企画第１段として、あなたの運営ノードを取材しに行きます！希望される方は７月２日～７月３日２４時の間で、このTwitterアカウントをフォローの上、いいね＆リツイートしてください。
あたれらで３ノード決定してDM等で取材させていたき、まとめた後じむはぶ広報アカウントからあなたのノードを宣伝します。毎月第１週開催予定。　広報：matsunoki

**Comment by temple1111** [comment]
Symbol & NEM Community Info の皆様こんばんわ、TEMPLEと申します。
mikunさんよりこのような場がある事を教えて頂き広報申請に参りました。
※mikunさん教えて頂きありがとうございました。

今回広報申請したい内容は、個人トークンの活用で
先日Twitterで発信した内容と同じなのですが、

【ブロックチェーンを使ったポイントカード】の広報申請です。

アルカナにて作成した個人トークンにリボーカブル機能を付けて
ブロックチェーンを使ったポイントサービスを様々な店舗で活用できれば
ポイントカードの管理や紛失など様々な煩わしい事が改善されるのではないでしょうか？
ポイントだけでは無く店舗の利用履歴も同様に出来るのではとも思います。
今回素人ながら、SYMBOLコミュニティの皆さんの情報を元に
コードを張り合わせてなんとか形に出来たのですが、
※こちらが記事になります。[templeroyce.site/blog/](https://t.co/PR6ScE8y5c)
お客様ごとにファイルを作ってGITHUBにアップし公開している状況で、
少し手間がかかるので、数が多くなってくると、負担になり続かなくなってきそうでして・・・

そこで、店舗側のベースのサイトにお客様が自身のアドレスでアクセスしたら
・お客様名・お客様アドレス・ポイント残高・店舗名・背景画像等が
表示されるように出来れば店舗の負担も軽減されると思います。
現在の私の技術力では実現が難しく、
この様な問題のアドバイスや改善案もかねて広報願いたいと思っているのですが、
こういった内容でも大丈夫なのでしょうか？

**Comment by mikunNEM** [comment]
@temple1111 さん
nem Japan UserGroup の Discord には参加されていますか？
Symbolの開発者が集まるDiscordになります。
➡️https://discord.gg/5CKEnxsJkX
技術的な部分でしたら、こちらで質問していただくと皆さんが優しくアドバイスをしていただけると思います☺️

広報ツイートに関しては、基本的に内容はSymbolやNEMに関する事でしたら何でも大丈夫です。
ツイートなので140文字以内という制限はありますが。

**Comment by temple1111** [comment]
mikunさんありがとうございます🙏
discordで聞くことができるのですね🙋
いちど聞いてみます🫡
ありがとうございます！

**Comment by ymuichiro** [comment]
掲載依頼： Symbol Web Site 開発 チームより

以下の通り、掲載を依頼したいです。

### ツイート内容
**tweet申請した者のアカウント**
https://twitter.com/faunsu19000

**広報文**
#Symbol Webサイトの開発チームがコミュニティより発足しました

チームの運用はDAOみたいな形式を目指しています

図のような開発の貢献に応じて開発参加者へ報酬を支払う仕組みを取ります

報酬を維持する為、専用ノードへの委任者を募集します。是非ご参加お願い致します
https://symbol-tools.com/symbolTools/view/tool/nodeDetails.html?inputHostName=d-01-pi-net.d-world.fun

**投稿日**
おまかせ

**挿絵**

<img width="1209" alt="image" src="https://user-images.githubusercontent.com/47295014/180641467-7df3e64e-a5b3-4ff5-a393-0d930fa3a409.png">

<img width="1482" alt="image" src="https://user-images.githubusercontent.com/47295014/180641415-fa6c29e2-eb65-49b3-b202-28413521a23e.png">

<img width="1423" alt="image" src="https://user-images.githubusercontent.com/47295014/180641431-bbad8400-3ceb-412c-8708-1defe36114b2.png">

**Comment by ymuichiro** [comment]
すみません。上に投稿したやつより先に投稿して欲しいやつが出ました。

掲載依頼： Symbol Desktop Wallet 開発チームより

以下の通り、掲載を依頼したいです。

ツイート内容
tweet申請した者のアカウント
https://twitter.com/faunsu19000

広報文
#Symbol Desktop Wallet の改善が進んでいます。WEB3は自己防衛の意識も大事ですが、より安全に参加して貰える環境を作っていきたいと考えます

そんな中、ウォレットのUIについて意見を頂戴したいと思っています

以下フォームへの投稿に是非、協力頂けないでしょうか

https://forms.gle/YoMJZTATGh65ChAy8

投稿日
できればちょっと早め

挿絵
<img width="1250" alt="image" src="https://user-images.githubusercontent.com/47295014/180654209-b24338a1-4579-4b29-a304-e9fd5efb4425.png">

**Comment by matsuno3** [comment]
上記２点　７時５０分、８時　に予約ツイートしました。

**Comment by ymuichiro** [comment]
ありがとうございます！
早速回答入り始めました

**Comment by honanem** [comment]
https://twitter.com/honanem/status/1551948482247663618?s=20&t=vRoxf_jI0MzmFDlnCW6LqA

https://twitter.com/honanem/status/1551948484827181056?s=20&t=vRoxf_jI0MzmFDlnCW6LqA

上記2つのツイートをリツイートしてちょーよ

**Comment by mikunNEM** [comment]
上記2つリツイートしました👍

**Comment by honanem** [comment]
ありがとうございます！

**Comment by matsuno3** [comment]
7月31日にみやま市の東照寺である、サマーマルシェにお細工もの秀虹@shukou_u 出店します！
お時間がある方宜しければご来場下さい！
ただ、この暑い最中に屋根無し駐車場での開催のため、熱中症にはくれぐれもお気をつけ下さい🙇‍♀️
#symbol決済　　https://twitter.com/yureyureyurei/status/1550720146872074241　広報者　matsunoki

**Comment by matsuno3** [comment]
こちらに移行します。
https://github.com/ymuichiro/symbol_japan_forum/issues/44
