### ISSUE TITLE
アート作品NFTをプラットフォーム外でも自由に使いたい？

### ISSUE THREAD

**Issue by matsuno3** [ymuichiro/symbol_japan_forum#30]
コチラは
[NFTの純度指標をデータにして第三者にわかるガイドライン的なものを作りたい](https://github.com/ymuichiro/symbol_japan_forum/issues/29)から派生しました。
様々なNFTがありますが、
・プラットフォーム外で使うニーズや、方法
・技術的な問題、技術的な解決方法
・今作者が抱えている問題、その解決方法
・保持者が抱えている問題、その解決方法
その他付随する情報、話題
を扱うスレッドです。
githubにしり込みしちゃう人の為にユーザー登録マニュアル作りました。
[https://nemlog.nem.social/blog/76331](https://nemlog.nem.social/blog/76331)

**Comment by ymuichiro** [comment]
@kooooO
これはこっち側だと思うのでリンクしておきます

https://github.com/ymuichiro/symbol_japan_forum/issues/2#issuecomment-1112872452

**Comment by koooo0** [comment]
確かに、NFTのプラットフォーム外の利用方法の問題かもですね。。。
open sea ってそもそもNFTなのだろうか・・・うごごごご

**Comment by ymuichiro** [comment]
NFTの定義で話した結果としてはOpenSeaもNFTといえると思います

ただし、その保存先の信頼性がOpenSeaとCOMSAでは異なるくらい

NFT=Token

として

Tokenの発行=電子署名

とすると、参照先コンテンツが消えた場合のNFTアートの扱いは、電子署名時の契約に明記しておくべきだと思った

※ 消費者側が守られていない

**Comment by ymuichiro** [comment]
作者、消費者両方の課題として、この契約時の条項がすっぽ抜けてるのは課題だと思う
（ NFTの外の話として ）

面白系の対応案としては、パブリックな公共性の高いNameSpaceを立てておいてそのMetaTagに契約条項を添付
※ パターン別に

そのIDか何かを出品時に参照しておけば、後の紛争防止になるのではと提案します

※ みんな契約に詳しいわけではないのでテンプレートとして扱うべきという点から
※ ただし、法務の専門家がゴロゴロしているとは思わないのでクリエイティブコモンズライセンスの参照が妥協点とも感じる

**Comment by matsuno3** [comment]
契約という意味では
https://symbol.openapostille.com/
オープンアポスティーユ　使う手もあるけど自動化されてないから手数はかかりますね。

**Comment by ymuichiro** [comment]
NFTへの署名（電子署名）とオープンアポスティーユだと役割一緒でNFTの署名と被ると思ってるんですが、違いって何かありましたっけ。

**Comment by matsuno3** [comment]
NFTへ署名されたデータとその画像データが、OpeningLineさんのサーバーに保存され、WEBを通して不特定多数からのアクセスができます。オープンアポスティーユ自体のサービスはSymbolアポスティーユ専用の保存庫なのでNFTとは異なりますね。

**Comment by patapiron** [comment]
フルオンチェーン型以外のNFTとなったNFTアートの売買契約（作品の参照や再生不可能になった際の条件等を含め）をNFTないしオープンアポスティーユを使用して確認するというおふたりのやりとりは興味がありますね。

ただ、もう少し雑多で平易なことも話題にしていきたいのでちょっと別な話題を
クリエイターさんも購入者も「COMSAで売れ残ったNFTアートを」
①COMSA外でSymbolチェーンの上で売りたい（使いたい）。
②他のチェーンにNFTとして登録して売りたい（使いたい）。
という需要はあると思います。これだけでも結構なボリュームになるかもですが、とりあえずここにぶら下げてていいですか？別スレの方がいいですか？
（おそらく、COMSA利用のクリエイターさんはSymbolの機能に惚れ込んでという方もいる一方、エンドースメントと日本円受領という簡便さに惹かれた方も多いと思います。技術的な部分に明るくない方もいらっしゃるかもしれません。）

**Comment by patapiron** [comment]
こういうツイートに対して、「COMSAに登録したSymbolアカウントに紐づいたウォレット使って、作品のNFTをエンドサーさんに送信できますよ。」と説明して理解し実行できる方がどのくらいいるのか気になります。

https://twitter.com/kuraki_pokoron/status/1520190368612249600?s=20&t=o1n3kQQY6zbhXZVk4KQixw

A：エンドーサーさんに渡したい作品のモザイクを特定する方法。（実はこれが自分もよくわかりません）
B：ウォレットDLと秘密鍵でのアカウント復元（ここで秘密鍵がないなどの事態も）
C：モザイク送信の基本操作
とハードルがあります。B・Cは説明動画がすでにあるので、Aがキーですかね。

**Comment by matsuno3** [comment]
＞「COMSAに登録したSymbolアカウントに紐づいたウォレット使って、作品のNFTをエンドサーさんに送信できますよ。」

残念ながらCOMSAの不正転送防止の仕組みが導入されているっぽい為、正常に出品できなくなります。
よって、できない。ということをのののんさんとkotopapaさんが検証しています。
https://nemlog.nem.social/blog/74945

**Comment by matsuno3** [comment]
https://twitter.com/faunsu19000/status/1520317962028154880
一見解決したように見えますけど、将来異なった端末で操作することになったら出品できなくなるのではないか。と思いとりあえずリンク張った。

**Comment by patapiron** [comment]
閲覧は可能なんですかね？
COMSAでの出品不可を双方了解の上で「閲覧のみ可能な記念NFT」みたいな存在としてしかだめ。
直接交渉売買のみ可という感じになりますでしょうか？

**Comment by matsuno3** [comment]
COMSAプラットフォームを通しての売買は可能です。
プラットフォーム外（正確には所有しているウォレットアドレス以外のアドレス）にトークンを転送することも可能ですが、COMSA上では購入したアドレスのみ出品可能な状態になるため、事実上出品不可能になります。

**Comment by patapiron** [comment]
「COMSAで登録のNFT」＋「COMSAでの売買履歴上の最終アドレスに保有」＝【COMSAへの出品可能】＋【閲覧が可能】

「COMSAで登録のNFTがCOMSAでの売買履歴上の最終アドレス以外で保有」＝COMSAへ出品不可能＆閲覧不可

ということになるでしょうか？

**Comment by patapiron** [comment]
自分のCOMSAアカウントとそれ以外のアカウントで試してみましたが、別アカウントに移してもarcanaウォレットなどで閲覧は可能でしたので、
クリエーターさん「売れ残るくらいならエンドーサーさんにあげたい」
エンドーサー「作品が閲覧できる手段があり、出品はしなくていい」
ということなら一般的なモザイク送信でのやりとりも選択肢にはなるのかもですね。本来はCOMSA側にその機能を付けてもらえればいいのでしょうけど。

**Comment by ymuichiro** [comment]
ちょっと話がそれるけど、COMSAに最近出品してみた中で、気になった点をまとめて規約形式にしてみた
https://docs.google.com/document/d/1bGsrBXXbWLr3wpuoIGUayx4a6d8W_t14HLfgA6F-__Y/edit?usp=sharing

**Comment by patapiron** [comment]
> ちょっと話がそれるけど、COMSAに最近出品してみた中で、気になった点をまとめて規約形式にしてみた https://docs.google.com/document/d/1bGsrBXXbWLr3wpuoIGUayx4a6d8W_t14HLfgA6F-__Y/edit?usp=sharing


最近、NFTの売買に現物の特典を付けたり、何か実物の商品の「鑑定書OR品質保証書」的なものをNFTとして、COMSAで売買（購入者は現物を別途受けとれる）しようとするアイディアを見かけました。

①1次販売者の意図通りに、2次販売以降「NFT＋実物」がリンクして売買されるのかどうか？
②2次販売の際に、COMSAプラットホーム外でのNFTの受け渡しをして出品者への手数料支払いを逃れる
など心配な点があり、ymuichiroさんの作成されたような規約をしっかり確認する方がよい場合があるのではと思った次第です。

**Comment by ymuichiro** [comment]
@patapiron まぁ心配な人はかっちりした規約をつけよう！くらいでも良いかもしれませんが、トラブル防止に向けてこんな規約をブラッシュアップしておいて、雛形として展開するのはいいかななんて思ってます

**Comment by koooo0** [comment]
イベント運営になればアートNFTでも割と自由に使えることがわかりました
