### ISSUE TITLE
NEMJAPANの新しい名称募集します【１５日２４時迄】

### ISSUE THREAD

**Issue by matsuno3** [ymuichiro/symbol_japan_forum#38]
下記アドレスの新しい名称を決定します。
[https://twitter.com/NEM_Japan](https://twitter.com/NEM_Japan)

Symbolコミュニティー広報の役割を持たせますので、
ご自由に考えて投稿ください。
NEMLOG記事コメントでも募集します。
[https://nemlog.nem.social/blog/76423](https://nemlog.nem.social/blog/76423)

テーマフレーズ
コミュニティーファースト

行動指針は下記のとおりです。
・助けられる範囲で助けあいます。
・教えられる範囲で教えあいます。
・活動している人を応援しあいます。

具体的な活動として下記を行います。
・広報力の弱い人の補助を行い、隠れた有益な情報を発信します。 　
じむはぶに窓口を設け広報tweetする内容を募集します。 　
※運営者も指定された手順に従い広報します。
・直接価格に関係するような一次情報は公式窓口にお任せし取り扱いません。
・１年間続け、結果をもとに改善更新を行います。

管理者　mikun matsunoki

**Comment by ymuichiro** [comment]
## 名称案
- SYMBOLNEM_コミュニティチーム
- SYMBOLNEM_ヘルプチーム

## 考えたこと
- Symbol/NEMは今後よりGlobalであるべきだと思うので、Japanとか日本というワードはつけない方がいいかも？
- Symbol/NEMに詳しくない人がぱっとみてわかる名称の方が良いかな？と思った

**Comment by mikunNEM** [comment]
まんまで「じむはぶPR」「じむはぶ広報」とか🥸

**Comment by Cat-008** [comment]
知らない方への訴求力を考えると

Symbol/NEM_web3チーム とか🤔

**Comment by honanem** [comment]
・Symbol＆NEM Community
・Symboler＆NEMbers！
・Welcome to Symbol＆NEM
・ムーニーしねしね団

**Comment by YUTOpian** [comment]
【新しい名称案】
Symbol Japan Community
Symbol コミュニティ窓口

コミュニティーファーストである事やSymbolの普及促進のことを考えると、この名称がシンプルで分かりやすいと考えました。
Symbol/NEMという2つの名前を並べるよりは、Symbolとした方がシンプルで良いと思いました。またSymbolという製品の中にNEMがあるので、Symbolのみでいいのではと考えています。

**Comment by honanem** [comment]
Symboler＆NEMber cheering party

**Comment by matsuno3** [comment]
柔い表現のほうがクレーム少なくていいなあとか思うので

じむはぶコミュニティー情報局
しんぼる通信

**Comment by honanem** [comment]
海外の人も使えるように、せめて名前だけでも英語にしたほうが良いと思うんじゃよ

**Comment by YUTOpian** [comment]
新しい名称案として
Symbol Japan Community
Symbol コミュニティ窓口
を紹介したけど、Japanはない方がいいとか、日本語を入れない方がいいと考えるならば、以下のような名称案も考えられます。
Symbol News
Symbol Ecosystem 
Symbol Ecosystem News
Symbol Community News

**Comment by mikunNEM** [comment]
NEM Japanテレグラム(Discordのjp)の方 でもらったものも載せときます。

NEM OFFICAL FOR JAPAN
nem家元
NEM 有志の会

OFFICALは無しですね😅
独自の名前にして欲しいという意見も有
