### ISSUE TITLE
Symbolアイディアチップ

### ISSUE THREAD

**Issue by matsuno3** [ymuichiro/symbol_japan_forum#39]
ふと思った瞬間の断片的なアイディアが役に立つことにあります。
なんでも書いてみてください。

**Comment by matsuno3** [comment]
https://twitter.com/taikoozisan/status/1525222109836111872
特定の場所に行ったらトークンを自動で得られる機能なんて、難しい？
もちろん事前登録は必要。

〇〇巡りをするとトークンが得られて、コンプするとなにか貰えて…
みたいなの、できないかな。

**Comment by ymuichiro** [comment]
やり方

- NFC
- GPSの座標情報（ただし、スマホの機能で詐称可能）
- 日替わりQRコード
- 現地で合言葉

**Comment by Cat-008** [comment]
> られて

ボーさんのイチゴのGPSマッチング機能で対応できるのではないでしょうか？
確か半径何メートル以内の人にモザイクばら撒く等可能だったように思います。

https://ichigo-word.fun/

![Screenshot_2022-05-14-22-31-18-50_0b2fce7a16bf2b728d6ffa28c8d60efb.jpg](https://user-images.githubusercontent.com/103439710/168428001-5e1d2257-4a76-444f-b1fb-e41a78fb9fd9.jpg)

**Comment by matsuno3** [comment]
まとめたので日曜日夜に消去します！
