### ISSUE TITLE
【思いついたらいつでもOK】【じむはぶ広報】Symbol & NEM Community Info受付（書き込み）窓口

### ISSUE THREAD

**Issue by matsuno3** [ymuichiro/symbol_japan_forum#44]
下記の手順・ルールにより広報に使用することができます。

**Symbolに関連する配信したい情報。**（ノード運営情報、計画、運営、企画募集、アイディア募集、アンケート等）

**【ツイート内容】**
・tweet申請した人のアカウント（自己、他推、可能です）
・内容
※法律に触れる文面、サービス案内等は禁止します

**【手順】**
受付窓口スレッドにコメントで情報をお書きください。
必要に応じて修正後（文字数等）tweetします。
※時間指定、日付指定希望がある場合は対象文の最後にお書きください。

**【トラブル発生時の対応】**
トラブル発生確認後、活動を停止します。
活動再開は、原因特定、原因対策、コミュニティーアンケート等でコンセンサスを取った後、再開されます。

**【免責事項】**
ツイート内容によるトラブルは申請者が責任を負います。
他推の場合のトラブルに関しても申請者が責任を負います。
こちらの機能はtweet広報窓口であり、他の機能を有しません。

**【運営方針】**
コミュニティーファースト

**【行動指針】**
・助けられる範囲で助けあいます。
・教えられる範囲で教えあいます。
・活動している人を応援しあいます。

**【活動内容】**
・広報の補助を行い、隠れた有益な情報を発信します。
　じむはぶに窓口を設け広報tweetする内容を募集します。

**Comment by mikunNEM** [comment]
Symbol デスクトップウォレット(v1.0.11) がリリースされました👛

デフォルトの設定では、不明なアグボンへの署名は許可されていません(アグボン詐欺対策)

他、バグ修正や改善が行われています✨

広報者:mikun

https://github.com/symbol/desktop-wallet/releases/tag/v1.0.11

**Comment by honanem** [comment]
🔽下記内容のツイートをお願いします

NPO法人NEM技術普及推進会『NEMTUS』は、コアデブから150万XYMと150万XEMの寄付を受け、NEMとSymbolの社会への普及に向けて様々な活動、支援を行っていきます
ぜひNEMTUSアカウントをフォローしてください
https://twitter.com/NemtusOfficial

**Comment by mikunNEM** [comment]
NEMTUSでは、NEM/Symbolコミュニティの皆さんが、LT(ライトニングトーク)形式で様々な発表や報告、宣伝などをすることのできる、月に一回開催されるメタバース会場「月間NEMTUS」を開始します。

第１回 : 8月27日(土)21:00〜22:30

登壇者募集中です💁‍♀️
https://nemtus.com/monthly-nemtus1/

広報者:mikun
#Symbol #NEMTUS

**Comment by matsuno3** [comment]
デスクトップウォレット更新に伴い、
アグボン詐欺に尽力していたメンバーの１人、Sayoさんの
導入マニュアルが更新されました。
https://nemlog.nem.social/blog/72670#C-1

皆に教えてあげてね？
#Symbol #初心者マニュアル

広報者:matsunoki

**Comment by mikunNEM** [comment]
Opening Line の Daokaさんが登壇されます✨

#Symbol ブロックチェーンの社会実装の取り組みについてお話を聞いてみましょう😊

お時間ある方は是非ご参加ください✨

広報者:mikun

https://twitter.com/daokatrade/status/1562381465844731906?s=21&t=BwM8imetz5_12v6XeL3scg

**Comment by USB2021** [comment]
#HEXA　で取り扱いが始まる仮想通貨XYM（ｼﾞﾑ）
HEXA取引所のウォレットと一緒に
自分用のXYMウォレットを持つことをお勧めします。
「アルカナウォレット」
簡単で便利でオススメです。

ios
https://apps.apple.com/jp/app/arcana-wallet/id1603599435
Android
https://play.google.com/store/apps/details?id=com.shu.software.symbol_arcana

インストール方法
https://nemlog.nem.social/blog/74066#C-1

**Comment by USB2021** [comment]
上記のTweet拡散お願いいたします。またESSANがHEXAでのXYM新規の方のサポートをツイートしておりますので
気が付いたらサポートお願いします。COMSAより規模が大きくオープンシーで活動されてる方も多く参加してるNFTマーケットです。来週からXYMでの支払いも可能になりますので、コミュニティで新規の方サポートしてあげてください。
SYMBOLと書いてジム？というくらいの新規の方なので、時々XYMで検索を見かけたらディスコードを見てとか、ネムログで調べろとかではなく　ツイートでリンクを置いてあげるという風に初心者に優しいサポートをお願いします

**Comment by mikunNEM** [comment]
トマティーナって何？👀
それは毎年8月31日に行われるトマトを投げるイベントです🍅✨
hossiiii さんがツリーにしてまとめてくれているので是非確認してみてください💁‍♀️
広報者:mikun

#Symbol  #トマティーナ
https://twitter.com/hossiiii1/status/1564359038703308800?s=20&t=mOvAltC-9w6MS7E-l5w1kg

**Comment by mikunNEM** [comment]
📢NEMTUSからのお知らせです。
🥳2022年10月29日(土曜日) 午後～夜に「 #Symbol 秋祭り」開催に向けて企画進行中！
コミュニティのみなさんと一緒に楽しいイベントにしたいと思っているので、何かやってみたい方は、ぜひお気軽に #NEMTUS までお声かけください🙏

https://nemtus.com/nemtus-fall-festival-to-be-held/

**Comment by mikunNEM** [comment]
暗号資産(Crypto Tokens)と「証券」について

とても大事な内容だと思うので皆さん是非読んでみてください👀
広報者: mikun

https://nemlog.nem.social/blog/77063

**Comment by mikunNEM** [comment]
月刊NEMTUSでは、登壇者を募集しています。
お気軽にご応募ください☺️
広報者: mikun
#NEMTUS #Symbol #NEM

https://twitter.com/NemtusOfficial/status/1569975057287630848?s=20&t=Vf5O7nk9f0yk4Gf7ouTd2g

**Comment by honanem** [comment]
Symbol・NEMの”日本語漢字名”を考えよう https://docs.google.com/forms/d/e/1FAIpQLSfoyHZwEB_-YXHcps-Hy9wFo4pmpOtTLispdsOzD_AmWxqRNw/viewform?usp=fb_send_twt 

#Symbol ＃NEM の日本語漢字名（当て字）を考えるコンテスト開催！
採用者に賞金100XYM！
詳しい条件は🔽フォーム内の説明を読んでね！
よろしくお願いします！

広報者:honanem
