### ISSUE TITLE
Symbol 便利ツール開発者 意見交換用

### ISSUE THREAD

**Issue by ymuichiro** [ymuichiro/symbol_japan_forum#8]
Symbolで便利ツール（Webサービスなど）を開発している方、こちらでもし宜しければ意見交換してください！
例えば開発中に困った事や、工夫したこと、他税制周りで気になった事、等、色々投稿してみて頂ければ幸いです！

ちなみにゲーム開発系は別トピックがありますので、そちらを参照ください

**Comment by ounziw** [comment]
WordPressのブロックエディタで xym価格を表示するプラグインを作成した。
https://github.com/ounziw/xymprice
価格情報は api.coingecko.com から取得。

困ることは、PHP用のSDKがまだ無いっぽいので、複雑なことをWordPress上で実現するのは現状では難しい。

**Comment by ymuichiro** [comment]
ちなみにこれはSDKのメンテナーに提案してもいんじゃないかと思っているのですが、各SDKできることと、REST APIの出来ることって被っているので、SDKの範囲を縮小 --> 対応言語を増やす、という提案は受け入れられないかしら

単純に言語を増やそうはリソース増やさないと厳しいだろうし

**Comment by 44uk** [comment]
> SDKの範囲を縮小
はもうjs-sdkとpython-sdkではその方向に向かっているので、これらをお手本にインターフェイスのルールだけ揃えたsdkを作ればいいと思います。
多分そんなに難しくない。チャンスですよ(?!)

**Comment by ymuichiro** [comment]
> SDKの範囲を縮小 --> 対応言語を増やすという方針で進むとは思いますが、PHPについては強いプッシュがないとコアと呼ばれる人には響きにくくてなかなか着手されないのでは？と思っています。

既に縮小の流れだったんですね
（ 確か縮小の話が上がった後、一度維持の流れになったと思っていたので勘違いしていました ）

> はもうjs-sdkとpython-sdkではその方向に向かっているので、これらをお手本にインターフェイスのルールだけ揃えたsdkを作ればいいと思います。

そうですね。私もこのまま縮小して広げる流れは適切だと思います。

---

ただ、取り敢えずPHPも増やしてくれっていうのは難しいと思っています。
何か良い根拠ってないですかね。 wordpress と相性が良い点かな？
（ どうせ提案するなら何かデータも示したい ）
後、これは私よく分からずいいますが、パーツだけ貰ってコミュニティ側で作るような事は難しいだろうか
　↓ これのパターン
https://github.com/0x070696E65/Symnity

**Comment by ymuichiro** [comment]
@0x070696E65 早速ありがとうございます！PHPの開発希望者で集まれば案外すぐ出来そうなスケジュール感？
他の方のご意見集めつつ、コア開発者にPHPニーズを揃えて提案かけていくか、自分らでやってしまうか、決めてしまいましょう（ cat-bufferとかの情報は @0x070696E65 ご協力お願いするかも）

**Comment by 0x070696E65** [comment]
あ、、でも確か僕とplanetさんが作ってた時と色々変わっててそもそもcatbuffer使わないか、もしくは大きく変更があったような、、、なのでそのへんは力になれないかもですが、なんか違うところでｗ

**Comment by 44uk** [comment]
https://docs.symbol.dev/ja/guidelines/generating-transaction-builders.html
https://docs.symbol.dev/ja/guidelines/sdk-development.html
ここにSDKガイドラインはあるけど…これ内容が古いな。
cat-bufferの節とかは役に立ちそうだけど、全体としてはあんまり更新されてないと思います。
というか、まだ新SDKについてってあんまりちゃんと告知というか、話に上がってない気がする…。

**Comment by 44uk** [comment]
https://docs.symbol.dev/ja/guides/index.html
それを言ってしまうと、ガイド以下の `方法 #02: SDK を使用する` で書いてあるコードサンプルは全部 `Deprecated` してしまうわけだがｗ

**Comment by xembook** [comment]
PHPerKaigi とかいう、声かけられそうな面白そうな会議がちょうど終わったとこだった。
https://phperkaigi.jp/2022/

スポンサー見てるとメルカリとか有名どころが支援してますね。

**Comment by 0x070696E65** [comment]
https://github.com/symbol/symbol/tree/dev/sdk/javascript/generator
もうここかどうかも分からんぐらい気持ちいいぐらいに違っててワケワカメでした

**Comment by xembook** [comment]
> ただ、取り敢えずPHPも増やしてくれっていうのは難しいと思っています。
何か良い根拠ってないですかね。 wordpress と相性が良い点かな？

現場で圧倒的に使われている言語ですよね。
https://type.jp/et/feature/18404/

> [2021年にW3Techsが発表したデータ](https://w3techs.com/technologies/history_overview/programming_language)によると、世界中で公開されているWebサイトのうち、約79％のWebサイトにPHPが使用されているそうです。競合であるRubyやJavaが5％前後であることを考えると、PHPのシェアが圧倒的だということが分かります。
さらにGitHubが発表した「[長年にわたるトップ言語](https://octoverse.github.com/)」によると、PHPは第6位。PHPはリリースから20年以上もの間人気の言語として君臨していることが分かりますね。

**Comment by xembook** [comment]
新SDKについてはまだアルファ版なので（聞きました）、今後の方針もくみ取りつつの開発が必要になるかと思います。
かつ、シリアライズ＆署名周りの開発はミスの許されない地道な作業です。
現段階で俺がやる！っていう情熱的な人がいないのであれば資金調達して委託するのがベターかと思います。

**Comment by 44uk** [comment]
> 新SDKについてはまだアルファ版なので（聞きました）
たしかにエクスペリメンタルとも書いてあったし、まだちょっと様子見たほうがいいかもね。
ただ、便利スクリプトやらスニペットなんかはその開発に流用したりできそうだし、いまでも十分に役に立ちそうだから関数レベルで書いておくのは損がなさそう。

**Comment by xembook** [comment]
多用するトランザクションは決まってますしね。
phpでの署名まわりはJWSっていうライブラリを使うのが一般的なんだろうか。
https://stackoverflow.com/questions/68612396/sign-and-verify-jws-json-web-signature-with-ed25519-keypair

懸念点としては去年末にコアなコントリビュータが引退してPHP財団というのができたらしい。。。
https://qiita.com/rana_kualu/items/eaf97694f25a62f93a7e

**Comment by xembook** [comment]
あ、これphpの記事じゃなかったごめんなさい

**Comment by ymuichiro** [comment]
phpの対応って難しそうだったら裏側でcli使ったら解決するのかな
（phpのPaaS的サービスは使えないけど）

https://docs.symbol.dev/ja/cli.html#:~:text=Symbol%20CLI%20is%20an%20Open%20Source%20command-line%20interface,blockchain.%20The%20source%20code%20is%20available%20at%20GitHub.

懐かしのCLI

**Comment by 44uk** [comment]
`cli`でも `js-sdk` でも、シェル実行で値を渡して結果を貰ってまた`php`に戻ってくるとか。割と苦肉の作ですけど、やりたいことを実現するのはできる。

**Comment by ounziw** [comment]
> `cli`でも `js-sdk` でも、シェル実行で値を渡して結果を貰ってまた`php`に戻ってくるとか。割と苦肉の作ですけど、やりたいことを実現するのはできる。

自分で運営するウェブサイトで、サーバーの権限とかもあれば、この方法でも行けますね。
ただ、WordPressでプラグインで纏めようと思うと、この方法だとキツイですね。

**Comment by ymuichiro** [comment]
PHPにてトランザクション送信が行われた記事情報
https://discord.com/channels/871354712618856449/976814980970188840
